language: ruby
rvm:
  - 2.4.0

install:
  - bundle install
  - gem install jekyll
  - gem install jekyll-sitemap
  - gem install emoji_for_jekyll
  - gem install jekyll-readme-index

branches:
  only:
    - master

env:
  global:
    - JEKYLL_ENV=production

notifications:
  email:
     recipients:
       - dredhorse@breiden.net
     on_success: always
     on_failure: always

script:
    - bundle exec jekyll build --destination docs --config _config.yml

deploy:
  provider: pages
  local-dir: ./docs
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master