language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build

branches:
  only:
    - Source

env:
  global:
    - JEKYLL_ENV=production

notifications:
  email:
     recipients:
       - dredhorse@breiden.net
     on_success: always
     on_failure: always

deploy:
  provider: pages
  local_dir: docs
  target_branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: Source