theme: jekyll-theme-minimal
title: SnowWhite, a Hackintosh Story
email: dredhorse@breiden.net

# many other settings
# ...

# Any plugins within jekyll_plugin group from Gemfile
plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-paginate-v2
    - jekyll-seo-tag
    - jekyll-compose
    - jekyll-redirect-from
    - github-pages

# Exclude these files from the build process results.
# Prevents them from showing up in the master branch which 
# is the live site.
exclude:
    - docs
    - resources
    - images
    - vendor
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - Rakefile

	